CREATE TABLE USUARIO
(
  USUARIO VARCHAR2(20) NOT NULL
, SENHA CHARACTER VARYING(200) NOT NULL
, NOME CHARACTER VARYING(50) NOT NULL
, CONSTRAINT USUARIO_PK PRIMARY KEY
  (
    USUARIO
  )
  ENABLE
);
