CREATE TABLE "PROCODE_S2S"."PERMISSAO_USUARIO"
(
  CODIGO_PERMISSAO CHARACTER VARYING(50) NOT NULL
, ID_USUARIO INTEGER NOT NULL
, CONSTRAINT PERMISSAO_USUARIO_PK PRIMARY KEY
(
  CODIGO_PERMISSAO, ID_USUARIO
)
);

ALTER TABLE "PROCODE_S2S"."PERMISSAO_USUARIO"
ADD CONSTRAINT PERMISSAO_USUARIO_PERM FOREIGN KEY
(
  CODIGO_PERMISSAO
)
REFERENCES PERMISSAO
(
  CODIGO
)
ENABLE;

ALTER TABLE "PROCODE_S2S"."PERMISSAO_USUARIO"
ADD CONSTRAINT PERMISSAO_USUARIO_USER FOREIGN KEY
(
  ID_USUARIO
)
REFERENCES USUARIO
(
  ID
)
ENABLE;
