CREATE TABLE "PROCODE_S2S"."RECUSA_CLIENTE"
(
  ID INTEGER NOT NULL
, UCID VARCHAR2(16 BYTE) NOT NULL
, RECUSA CHARACTER VARYING(200) NOT NULL
, DATA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
, CONSTRAINT RECUSA_CLIENTE_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
);

ALTER TABLE "PROCODE_S2S"."RECUSA_CLIENTE"
ADD CONSTRAINT FK_ATENDIMENTO_RECUSA_CLIENTE FOREIGN KEY
(
  UCID
)
REFERENCES ATENDIMENTO
(
  UCID
)
ENABLE;
