CREATE TABLE "PROCODE_S2S"."USUARIO"
(
  ID INTEGER NOT NULL
, USUARIO CHARACTER VARYING(20) NOT NULL
, SENHA CHARACTER VARYING(20) NOT NULL
, NOME CHARACTER VARYING(20)
, CONSTRAINT USUARIO_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
);
